name: Release chart-api

on:
  push:
    branches:
      - main
    paths:
      - 'charts/api/**'

jobs:
  release:
    uses: ./.github/workflows/_release.yml
    with:
      path: charts/api
    secrets: inherit
